# Generated by Django 2.1.5 on 2020-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('proteins', models.IntegerField()),
            ],
        ),
    ]
