# Generated by Django 2.1.5 on 2020-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(help_text='Enter in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.IntegerField(help_text='Enter in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.IntegerField(help_text='Enter in grams'),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(help_text='Enter in cups or whole numbers'),
        ),
    ]
