# Generated by Django 2.2.10 on 2020-05-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcatalog', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
